version: '3'
services:
  dbpostgres:
    image: postgres:10
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

  app:
    build:
      context: .
    depends_on:
      - dbpostgres
    expose:
      - '8001'
    links:
      - dbpostgres
    ports:
      - '8001:8001'
    env_file:
      - .env.example
